# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce85438299ed39a80ae0d80640917ff6ff43f05bbce13ff3f04508f48eca246af7f3a054fc2b431befbca1686be004e3cb360a0b010525b71c840bf895cef89a

test:
  secret_key_base: 0bc505b1d325bc7cc0a71ea486b04c3585394432153ae3b60befced09f60f3aa220cd3c39cd342ea5b2899c18d5c969890be4d9df638daebc7de657acafbcbb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
